'use client';
import {useState,useEffect} from 'react';
import {Pause,Play,ChevronLeft,ChevronRight,ArrowUpRight,Download,Mail,Phone,Clock,MapPin,ExternalLink} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {WhatsAppIcon} from './whatsapp-icon';
import {pdf} from '@/lib/catalog';
const brands=[
 {id:'quimatic',name:'Quimatic Tapmatic',line:'Químicos para a indústria',families:['Usinagem e fluidos de corte','Manutenção e lubrificação','Tratamento de superfícies'],catalog:'https://www.quimatic.com.br/produtos/'},
 {id:'hch',name:'HCH',line:'Rolamentos',families:['Rolamentos de esferas','Aplicações industriais','Seleção por medida'],catalog:''},
 {id:'vibra-stop',name:'Vibra-Stop',line:'Controle de impacto e vibração',families:['Amortecedores de vibração','Apoios para máquinas','Controle de impacto'],catalog:''},
 {id:'kifix',name:'Kifix',line:'Grampos e sistemas de fixação',families:['Grampos de fixação','Dispositivos de aperto','Acessórios para montagem'],catalog:'https://www.kifix.com.br/catalogo/1_pt_BAIXACatalogoKIFIXCOMPLETO23_0.pdf'},
 {id:'merkbak',name:'Merkbak',line:'Componentes para máquinas',families:['Volantes e manípulos','Maçanetas e alavancas','Pés niveladores e puxadores'],catalog:pdf}
];
export function BrandPartners({onContact}:{onContact:(s:string)=>void}){
 const[paused,setPaused]=useState(false),[selected,setSelected]=useState<typeof brands[number]|null>(null),[index,setIndex]=useState(0);
 useEffect(()=>{if(paused||selected||matchMedia('(prefers-reduced-motion: reduce)').matches)return;const timer=setInterval(()=>setIndex(i=>(i+1)%brands.length),6000);return()=>clearInterval(timer)},[paused,selected,index]);
 const current=brands[index];
 return <><section className="brand-partners" aria-label="Marcas e seus catálogos"><div className="container"><div className="brand-exhibit"><div className="brand-intro"><h2>Boas conexões.<br/>Grandes marcas.</h2><p>Escolha uma marca e explore suas soluções.</p></div><button className="brand-current" onClick={()=>setSelected(current)} aria-label={`Abrir catálogo ${current.name}`}><img key={current.id} src={`/images/brands/${current.id}.jpg`} alt={current.name}/><div><strong>{current.name}</strong><small>{current.line}</small><small>Explorar catálogo <ArrowUpRight size={13} style={{display:'inline'}}/></small></div></button><div className="brand-controls"><span>{index+1} / {brands.length}</span><button aria-label="Marca anterior" onClick={()=>{setIndex(i=>(i+brands.length-1)%brands.length);setPaused(true)}}><ChevronLeft size={18}/></button><button aria-label={paused?'Retomar marcas':'Pausar marcas'} aria-pressed={paused} onClick={()=>setPaused(!paused)}>{paused?<Play size={16}/>:<Pause size={16}/>}</button><button aria-label="Próxima marca" onClick={()=>{setIndex(i=>(i+1)%brands.length);setPaused(true)}}><ChevronRight size={18}/></button></div></div><div className="brand-tabs" role="tablist" aria-label="Selecionar marca">{brands.map((b,i)=><button key={b.id} role="tab" data-name={b.name} aria-label={b.name} aria-selected={i===index} onClick={()=>{setIndex(i);setPaused(true)}}/>)}</div></div></section><Dialog open={!!selected} onOpenChange={v=>{if(!v)setSelected(null)}}><DialogContent className="brand-catalog-dialog"><DialogTitle>Catálogo {selected?.name}</DialogTitle><DialogDescription>{selected?.line}</DialogDescription>{selected&&<><img className="brand-catalog-logo" src={`/images/brands/${selected.id}.jpg`} alt={selected.name}/><div className="brand-families">{selected.families.map(f=><button key={f} onClick={()=>{setSelected(null);onContact(`Catálogo ${selected.name} — ${f}`)}}><strong>{f}</strong><span>Consultar linha com a Carol</span></button>)}</div><p className="micro">Seleção ilustrativa de famílias. Confirme especificações e disponibilidade com a equipe.</p>{selected.catalog?<a className="button primary full" href={selected.catalog} target="_blank" rel="noreferrer"><ExternalLink size={18}/>Abrir catálogo da marca</a>:<button className="button primary full" onClick={()=>{setSelected(null);onContact(`Solicitar catálogo ${selected.name}`)}}><Download size={18}/>Solicitar catálogo completo</button>}</>}</DialogContent></Dialog></>;
}
export function ContactDetails({onContact}:{onContact:(s:string)=>void}){
 return <section id="contatos" className="contact-details section"><div className="container"><div className="contact-details-heading"><h2>Pessoas de verdade.<br/>Soluções para ir além.</h2><p>No balcão de Joinville ou na tela, a parceria é a mesma.</p></div><div className="contact-details-grid"><article><div className="contact-label"><MapPin size={22}/><span>Loja física · Joinville / SC</span></div><h3>Seu ponto de encontro.</h3><a href="mailto:vendas@carolcomponentes.com.br"><Mail size={18}/>vendas@carolcomponentes.com.br</a><a href="tel:+554734350101"><Phone size={18}/>(47) 3435-0101</a><button onClick={()=>onContact('Atendimento loja física')}><WhatsAppIcon width={19} height={19}/>(47) 99618-0088 · WhatsApp</button><address>Rua Carlos Willy Boehm, 537 — Santo Antônio<br/>Joinville — SC · CEP 89218-301</address><div className="opening-hours"><Clock size={19}/><div><strong>Horário de funcionamento</strong><p>Segunda a quinta<br/>07h30–12h · 13h30–18h</p><p>Sexta-feira<br/>07h30–12h · 13h30–17h</p></div></div></article><article><div className="contact-label"><Mail size={22}/><span>Atendimento virtual · Todo o Brasil</span></div><h3>A Carol, onde você estiver.</h3><p>Envie um código, uma medida ou sua lista de componentes. Nossa equipe de Joinville acompanha sua cotação e combina a entrega.</p><a href="mailto:lojavirtual@carolcomponentes.com.br"><Mail size={18}/>lojavirtual@carolcomponentes.com.br</a><button onClick={()=>onContact('Atendimento virtual')}><WhatsAppIcon width={19} height={19}/>(47) 99618-0088 · WhatsApp</button><button className="button primary" onClick={()=>onContact('Atendimento virtual — cotação')}>Conversar sobre meu projeto</button></article></div></div></section>;
}
const payments=[['visa','Visa'],['mastercard','Mastercard'],['hipercard','Hipercard'],['amex','American Express'],['diners','Diners Club'],['aura','Aura'],['elo','Elo'],['discover','Discover'],['jcb','JCB'],['boleto','Boleto'],['bb','Banco do Brasil'],['bradesco','Bradesco'],['itau','Itaú']];
export function PaymentMethods(){return <section className="payment-methods" aria-labelledby="payments-title"><div className="container"><div className="payments-heading"><h2 id="payments-title">Seu projeto, suas condições.</h2><p>Consulte com a equipe as modalidades disponíveis e as condições da sua cotação.</p></div><ul className="payment-logos">{payments.map(([id,name],i)=><li key={id} style={{'--payment-index':i} as React.CSSProperties}><img src={`/images/payments/${id}.svg`} alt={name} width={76} height={48} loading="lazy"/><span>{name}</span></li>)}</ul></div></section>}
