import type {Product} from './catalog';
const columns=['id','slug','name','sku','brand','type','section','price','homepage','summary','description','weight','dimensions','categories','attributes'];
export async function exportCatalog(products:Product[]){
 const {Workbook}=await import('exceljs');const w=new Workbook();const s=w.addWorksheet('Produtos');s.addRow(columns);
 products.forEach(p=>s.addRow(columns.map(k=>k==='categories'?JSON.stringify(p.categories):k==='attributes'?JSON.stringify(p.attributes):k==='homepage'?(p.homepage?'SIM':'NÃO'):(p as unknown as Record<string,unknown>)[k]??'')));
 const v=w.addWorksheet('Medidas');v.addRow(['product_id','id','sku','label','weight','dimensions','attributes']);products.forEach(p=>p.variations.forEach(x=>v.addRow([p.id,x.id,x.sku,x.label,x.weight,x.dimensions,JSON.stringify(x.attributes)])));
 const help=w.addWorksheet('Orientações');['Edite Produtos e Medidas. Os IDs existentes devem ser mantidos. Novos produtos: use um ID inteiro positivo exclusivo.','A carga substitui todo o catálogo. Produtos ausentes serão removidos após confirmação.','Não altere os títulos das colunas. Categorias e atributos usam JSON; mantenha a estrutura do exemplo.','Não há coluna de fotos: imagens dos IDs preservados permanecem; adicione fotos dos novos itens na tela.','Homepage: exatamente 12 SIM para seleção personalizada; qualquer outra quantidade usa os 12 primeiros por nome.','Descrição é texto simples na administração; HTML original não pode ser editado para incluir scripts.'].forEach(t=>help.addRow([t]));
 for(const sh of [s,v]){sh.views=[{state:'frozen',ySplit:1}];sh.getRow(1).font={bold:true,color:{argb:'FFFFFFFF'}};sh.getRow(1).fill={type:'pattern',pattern:'solid',fgColor:{argb:'FF163C35'}};sh.columns.forEach(c=>c.width=24);sh.autoFilter={from:{row:1,column:1},to:{row:1,column:sh.columnCount}}}
 const b=await w.xlsx.writeBuffer();const u=URL.createObjectURL(new Blob([b as BlobPart],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}));const a=document.createElement('a');a.href=u;a.download='catalogo-carol-componentes.xlsx';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);
}
export async function importCatalog(file:File,current:Product[]){
 if(file.size>8_000_000)throw Error('Use uma planilha de até 8 MB.');const{Workbook}=await import('exceljs');const w=new Workbook();await w.xlsx.load(await file.arrayBuffer());const s=w.getWorksheet('Produtos'),v=w.getWorksheet('Medidas');if(!s||!v)throw Error('Use o modelo com as abas Produtos e Medidas.');
 if(s.rowCount>5001||v.rowCount>20001)throw Error('Limite: 5.000 produtos e 20.000 medidas.');
 const rows=(sh:typeof s,headers:string[])=>{if(headers.some((h,i)=>sh.getRow(1).getCell(i+1).value!==h))throw Error('As colunas do modelo foram alteradas.');const out:Record<string,string>[]=[];sh.eachRow((r,n)=>{if(n===1)return;const x:Record<string,string>={};headers.forEach((h,i)=>{const value=r.getCell(i+1).value;if(typeof value==='object'&&value!==null)throw Error(`Linha ${n}: use valores simples; fórmulas não são aceitas.`);x[h]=String(value??'')});if(Object.values(x).some(Boolean))out.push(x)});return out};
 const measures=rows(v,['product_id','id','sku','label','weight','dimensions','attributes']);const out=rows(s,columns).map((x,n)=>{try{const old=current.find(p=>p.id===Number(x.id));return {...x,id:Number(x.id),price:Number(x.price),homepage:x.homepage.toUpperCase()==='SIM',categories:JSON.parse(x.categories||'[]'),attributes:JSON.parse(x.attributes||'[]'),image:old?.image||'/images/photo-pending.svg',images:old?.images||[],variations:measures.filter(m=>Number(m.product_id)===Number(x.id)).map(m=>({...m,id:Number(m.id),attributes:JSON.parse(m.attributes||'[]'),image:old?.variations.find(z=>z.id===Number(m.id))?.image||null}))} as Product}catch{throw Error(`Produto na linha ${n+2}: confira categorias e atributos em JSON.`)}});
 if(measures.some(m=>!out.some(p=>p.id===Number(m.product_id))))throw Error('Há medidas sem um produto correspondente.');return out;
}
